<?php

namespace Pois\AttachmentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachmentRepository extends EntityRepository
{
    public function findByClientFilename($client, $file)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('a')
            ->from('PoisAttachmentBundle:Attachment','a')
            ->innerJoin('a.clients','c')            
            ->where('c.id=:id')            
            ->andWhere('a.path=:path')            
            // ->orderBy('m.created desc')
            ->setParameter('id', $client->getId())
            ->setParameter('path', $file)
            ;

        return $qb->getQuery()->getResult();
    }
}
